AutoShowWebApplication/Models/Drife.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


#nullable disable

namespace AutoShowWebApplication
{
    public partial class Drife
    {
        public Drife()
        {
            Cars = new HashSet<Car>();
        }

        public int DriveId { get; set; }
        [Display(Name = "Тип приводу")]
        public string DriveType { get; set; }

        public virtual ICollection<Car> Cars { get; set; }
    }
}

AutoShowWebApplication/Controllers/DrifesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using ClosedXML.Excel;
using AutoShowWebApplication.Models;
using AutoShowWebApplication;

namespace AutoShowWebApplication.Controllers
{
   
    public class DrifesController : Controller
    {
        private readonly AutoShowContext _context;

        public DrifesController(AutoShowContext context)
        {
            _context = context;
        }

        // GET: Drifes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Drives.ToListAsync());
        }

        // GET: Drifes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drife = await _context.Drives
                .FirstOrDefaultAsync(m => m.DriveId == id);
            if (drife == null)
            {
                return NotFound();
            }

            // return View(drife);
            return RedirectToAction("Index", "Cars", new { id = drife.DriveId, name = drife.DriveType });

        }

        // GET: Drifes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drifes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DriveId,DriveType")] Drife drife)
        {
            if (ModelState.IsValid)
            {
                _context.Add(drife);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(drife);
        }

        // GET: Drifes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drife = await _context.Drives.FindAsync(id);
            if (drife == null)
            {
                return NotFound();
            }
            return View(drife);
        }

        // POST: Drifes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DriveId,DriveType")] Drife drife)
        {
            if (id != drife.DriveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(drife);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DrifeExists(drife.DriveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(drife);
        }

        // GET: Drifes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drife = await _context.Drives
                .FirstOrDefaultAsync(m => m.DriveId == id);
            if (drife == null)
            {
                return NotFound();
            }

            return View(drife);
        }

        // POST: Drifes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var drife = await _context.Drives.FindAsync(id);
            _context.Drives.Remove(drife);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DrifeExists(int id)
        {
            return _context.Drives.Any(e => e.DriveId == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
                        {
                            //перегляд усіх листів (в даному випадку категорій)
                            foreach (IXLWorksheet worksheet in workBook.Worksheets)
                            {
                                //worksheet.Name - назва категорії. Пробуємо знайти в БД, якщо відсутня, то створюємо нову
                                Drife newcat;
                                var c = (from cat in _context.Drives
                                         where cat.DriveType.Contains(worksheet.Name)
                                         select cat).ToList();
                                if (c.Count > 0)
                                {
                                    newcat = c[0];
                                }
                                else
                                {
                                    newcat = new Drife();
                                    newcat.DriveType = worksheet.Name;
                                    
                                  
                                    _context.Drives.Add(newcat);
                                }
                                //перегляд усіх рядків                    
                                foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
                                {
                                    try
                                    {
                                        Car car = new Car();
                                        BodyType bt = new BodyType();
                                        car.BodyType = bt;
                                        Color cl = new Color();
                                        car.Color = cl;
                                        car.BodyType.BodyTypeNames = row.Cell(2).Value.ToString();
                                        car.Color.ColorName = row.Cell(3).Value.ToString();
                                       
                                        car.Drive = newcat;
                                        _context.Cars.Add(car);
                                       
                                        
                                        
                                            if (row.Cell(1).Value.ToString().Length > 0)
                                            {
                                                Model model;

                                                var a = (from aut in _context.Models
                                                         where aut.ModelName.Contains(row.Cell(1).Value.ToString())
                                                         select aut).ToList();
                                                if (a.Count > 0)
                                                {
                                                    model = a[0];
                                                car.ModelId = model.ModelId;

                                                }
                                                else
                                                {
                                                    model = new Model();
                                                    model.ModelName = row.Cell(1).Value.ToString();
                                                    
                                                    _context.Models.Add(model);
                                                }
                                            car.Model = model;
                                            }
                                        
                                    }
                                    catch (Exception e)
                                    {
                                        Console.WriteLine(e.Message);

                                    }
                                }
                            }
                        }
                    }
                }

                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Export()
        {
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var drives = _context.Drives.Include("Cars").ToList();
               
                foreach (var c in drives)
                {
                    var worksheet = workbook.Worksheets.Add(c.DriveType);

                    worksheet.Cell("A1").Value = "Модель";
                    worksheet.Cell("B1").Value = "Тип кузова";
                    worksheet.Cell("C1").Value = "Колір";
                    worksheet.Row(1).Style.Font.Bold = true;
                    var cars = c.Cars;

                    int j = 0;
                    foreach (var b in c.Cars)
                    {

AutoShowWebApplication/Views/Drifes/Create.cshtml
@model AutoShowWebApplication.Drife

@{
    ViewData["Title"] = "Create";
}

<h1>Додавання типу приводу</h1>

<h4>Тип приводу</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DriveType" class="control-label"></label>
                <input asp-for="DriveType" class="form-control" />
                <span asp-validation-for="DriveType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoShowWebApplication/Views/Drifes/Delete.cshtml
@model AutoShowWebApplication.Drife

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалення</h1>

<h3>Ви впевнені, що хочете видалити?</h3>
<div>
    <h4>Тип приводу</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DriveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriveType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DriveId" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Повернутися до списку</a>
    </form>
</div>

AutoShowWebApplication/Views/Drifes/Details.cshtml
@model AutoShowWebApplication.Drife
    <div style="padding:100px 0" class="container">

        @{
            ViewData["Title"] = "Details";
        }

        <h1>Деталі</h1>

        <div>
            <h4>Тип приводу</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.DriveType)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.DriveType)
                </dd>
            </dl>
        </div>
        @if (User.IsInRole("admin"))
        {
            <div>
                <a asp-action="Edit" asp-route-id="@Model.DriveId">Редагувати</a> |
                <a asp-action="Index">Повернутися до списку</a>
            </div>}
        @if (!User.IsInRole("admin"))
        {
            <div>

                <a asp-action="Index">Повернутися до списку</a>
            </div>}
        </div>

AutoShowWebApplication/Views/Drifes/Edit.cshtml
@model AutoShowWebApplication.Drife

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагування</h1>

<h4>Тип приводу</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DriveId" />
            <div class="form-group">
                <label asp-for="DriveType" class="control-label"></label>
                <input asp-for="DriveType" class="form-control" />
                <span asp-validation-for="DriveType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoShowWebApplication/Views/Drifes/Index.cshtml
@model IEnumerable<AutoShowWebApplication.Drife>
    <div style="padding:100px 0" class="container">

        @{
            ViewData["Title"] = "Типи приводів";
        }

        <h1>Список типів приводу</h1>
        @if (User.IsInRole("admin"))
        {
            <p>
                <a asp-action="Create">Додати тип приводу</a>
            </p>}



        <div>
            <h3>Оберіть exel-файл для заватаження</h3>
            @using (Html.BeginForm("Import", "Drifes", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
            {
                <div>
                    Завантажте Excel-файл:
                    <input type="file" name="fileExcel" id="fileExcel" />
                    <div>
                        <input type="submit" value="Завантажити" />
                    </div>
                </div>
            }
        </div>

        <div>
            <h3>Завантаження інформації в файл</h3>
            <a asp-action="Export">Завантаження</a>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.DriveType)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DriveType)
                        </td>
                        @if (User.IsInRole("admin"))
                        {
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.DriveId">Редагувати</a> |
                                <a asp-action="Details" asp-route-id="@item.DriveId">Деталі</a> |
                                <a asp-action="Delete" asp-route-id="@item.DriveId">Видалити</a>
                            </td>
                        }
                        @if (!User.IsInRole("admin"))
                        {
                            <td>

                                <a asp-action="Details" asp-route-id="@item.DriveId">Деталі</a>

                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>

        <div class="container">
            <div id="chart1"></div>
        </div>
        @section scripts{
            <script type "text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script>
                google.charts.load('current', { 'packages': ['corechart'] });
                google.charts.setOnLoadCallback(drawChart);

                function drawChart() {

                    $.get('/api/Values/JsonData', function (JsonData) {
                        data = google.visualization.arrayToDataTable(JsonData, false);
                        var option = {
                            title: "Співвідношення кількості автомобілів та типів приводу",
                            width: 500,
                            height: 400
                        };
                        chart = new google.visualization.PieChart(document.getElementById('chart1'));
                        chart.draw(data, option);
                    })
                }
            </script>
        }
</div>