AutoShowWebApplication/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoShowWebApplication;
using Microsoft.AspNetCore.Http;
using System.IO;
using AutoShowWebApplication.Models;
using AutoShowWebApplication.ViewModels;
using ClosedXML.Excel;

namespace AutoShowWebApplication.Controllers
{

    public class CarsController : Controller
    {

        private readonly AutoShowContext _context;

        public CarsController(AutoShowContext context)
        {
            _context = context;
        }
        private IEnumerable<Car> ApplyFilters(int? drive, int? color, int? year)
        {
            IEnumerable<Car> cars = from s in _context.Cars
                                                      .Include(x => x.Drive)
                                                      .Include(x => x.Color)
                                        //.Include(x => x.BodyType)
                                        //.Include(x => x.Model)
                                    select s;
            if (drive != null)
            {
                cars = cars.Where(c => c.DriveId == drive);
            }
            if (color != null)
            {
                cars = cars.Where(c => c.ColorId == color);
            }
            if (year != null)
            {
                cars = cars.Where(c => c.GraduationYear == year);
            }
            return cars;
        }
        // GET: Cars
        /*
        public async Task<IActionResult> IndexAuto()
        {
            return View(await _context.Cars.Include(j => j.BodyType).Include(j => j.Color).Include(j => j.Drive).Include(j => j.Model).ToListAsync());
            
        }*/
        public async Task<IActionResult> IndexAuto(int? drive, int? color, int? year)
        {
           // ViewBag.cars =  new SelectList(_context.Drives.OrderBy(s => s.DriveType), "DriveId", "DriveType").Append(new SelectListItem("Усі", null, true));
            //ViewData["DriveId"] = new SelectList(_context.Drives.OrderBy(s => s.DriveType), "DriveId", "DriveType").Append(new SelectListItem("Усі", null, true));
            CarsListViewModel listModelView = new CarsListViewModel(_context);
            listModelView.Cars = ApplyFilters(drive, color, year);
            return View(listModelView);
        }
       
        public async Task<IActionResult> Index(int? id, string? name)
        {
            //if (id == null) return RedirectToAction("Drifes", "Index");
            ViewBag.DriveId = id;
            ViewBag.DriveType = name;
            var autoByDrives = _context.Cars.Where(b => b.DriveId == id).Include(b => b.Drive).Include(j => j.Model).Include(j => j.BodyType).Include(j => j.Color);
            return View(await autoByDrives.ToListAsync());
        }

        /*
        public ActionResult IndexFilter(int? drive, int year)
        {
            IQueryable<Car> cars = _context.Cars.Include(c => c.Drive);
            if (drive != null &&  drive!= 0)
            {
                cars = cars.Where(c => c.DriveId == drive);
            }
            if (year != 0 && !year.Equals("Все"))
            {
                cars = cars.Where(c => c.GraduationYear == year);
            }

            List<Drive> drives = _context.Drives.ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            drives.Insert(0, new Drive { DriveType = "Всі", DriveId = 0 });

            DrivesListViewModel dlvm = new DrivesListViewModel
            {
                Cars = cars.ToList(),
                Drives = new SelectList(drives, "DriveId", "DriveType"),
                Years = new SelectList(new List<int>()
            {
                2019,
                2020,
                2021
            })
            };
            return View(dlvm);
        }
        */
        public async Task<IActionResult> IndexM(int? id, string? name)
        {
            //if (id == null) return RedirectToAction("Drifes", "IndexM");
            ViewBag.BodyTypeId = id;
            ViewBag.BodyTypeNames = name;
            var autoByBodyTypes = _context.Cars.Where(b => b.BodyTypeId == id).Include(b => b.BodyType).Include(j => j.Drive).Include(j => j.Model).Include(j => j.Color);
            return View(await autoByBodyTypes.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.BodyType)
                .Include(c => c.Color)
                .Include(c => c.Drive)
                .Include(c => c.Model)
                .FirstOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }
        // GET: Сars/Create

        public IActionResult CreateAuto()
        {
            ViewData["BodyTypeId"] = new SelectList(_context.BodyTypes, "BodyTypeId", "BodyTypeNames");
            ViewData["ColorId"] = new SelectList(_context.Colors, "ColorId", "ColorName");
            ViewData["DriveId"] = new SelectList(_context.Drives, "DriveId", "DriveType");
            ViewData["ModelId"] = new SelectList(_context.Models, "ModelId", "ModelName");

            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateAuto(CarViewModel cvm)
        {
            Car car = new Car
            {
                BodyTypeId = cvm.BodyTypeId,
                ColorId = cvm.ColorId,
                DriveId = cvm.DriveId,
                ModelId = cvm.ModelId,

                CarId = cvm.CarId,
                Price = cvm.Price,
                GraduationYear = cvm.GraduationYear,
                Description = cvm.Description,



            };
            if (ModelState.IsValid)
            {
                if (cvm.Image != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(cvm.Image.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)cvm.Image.Length);
                    }
                    // установка массива байтов
                    car.Image = imageData;
                }
                _context.Add(car);
                _context.SaveChanges();

                return RedirectToAction(nameof(IndexAuto));

            }
            ViewData["BodyTypeId"] = new SelectList(_context.BodyTypes, "BodyTypeId", "BodyTypeNames");
            ViewData["ColorId"] = new SelectList(_context.Colors, "ColorId", "ColorName");
            ViewData["DriveId"] = new SelectList(_context.Drives, "DriveId", "DriveType");
            ViewData["ModelId"] = new SelectList(_context.Models, "ModelId", "ModelName");
            return View(car);
        }
        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAuto([Bind("CarId,ModelId,Price,GraduationYear,BodyTypeId,ColorId,DriveId, Image")] Car car)
        {


            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexAuto));


            }
            ViewData["BodyTypeId"] = new SelectList(_context.BodyTypes, "BodyTypeId", "BodyTypeNames", car.BodyTypeId);
            ViewData["ColorId"] = new SelectList(_context.Colors, "ColorId", "ColorName", car.ColorId);
            ViewData["DriveId"] = new SelectList(_context.Drives, "DriveId", "DriveType", car.DriveId);
            ViewData["ModelId"] = new SelectList(_context.Models, "ModelId", "ModelName", car.ModelId);
            //  ViewData["PhotoId"] = new SelectList(_context.Photos, "PhotoId", "Image", car.PhotoId);

            return View(car);


        }*/
        public IActionResult Create(int driveId)
        {
            ViewData["BodyTypeId"] = new SelectList(_context.BodyTypes, "BodyTypeId", "BodyTypeNames");
            ViewData["ColorId"] = new SelectList(_context.Colors, "ColorId", "ColorName");
            //ViewData["DriveId"] = new SelectList(_context.Drives, "DriveId", "DriveType");
            ViewData["ModelId"] = new SelectList(_context.Models, "ModelId", "ModelName");



            ViewBag.DriveId = driveId;
            ViewBag.DriveType = _context.Drives.Where(c => c.DriveId == driveId).FirstOrDefault().DriveType;


            return View();
        }

        public IActionResult CreateM(int bodytypeId)
        {
            //ViewData["BodyTypeId"] = new SelectList(_context.BodyTypes, "BodyTypeId", "BodyTypeNames");
            ViewData["ColorId"] = new SelectList(_context.Colors, "ColorId", "ColorName");
            ViewData["DriveId"] = new SelectList(_context.Drives, "DriveId", "DriveType");
            ViewData["ModelId"] = new SelectList(_context.Models, "ModelId", "ModelName");
            ViewData["PhotoId"] = new SelectList(_context.Models, "PhotoId", "Image");

            ViewBag.BodyTypeId = bodytypeId;
            ViewBag.BodyTypeNames = _context.BodyTypes.Where(c => c.BodyTypeId == bodytypeId).FirstOrDefault().BodyTypeNames;



            return View();
        }

        // POST: Cars/Create

AutoShowWebApplication/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShowWebApplication.Models;
using AutoShowWebApplication.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace AutoShowWebApplication.Controllers
{
    
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());
        public IActionResult UserList() => View(_userManager.Users.ToList());
        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string userId)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                //список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // список ролей, які було додано
                var addedRoles = roles.Except(userRoles);
                // список ролей, які було видалено
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

    }
}

AutoShowWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Infiniti</title>
    <link rel="stylesheet" href="../css/style.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.0/css/all.css" integrity="sha384-OLYO0LymqQ+uHXELyx93kblK5YIS3B2ZfLGBmsJaUyor7CpMTBsahDHByqSuWW+q" crossorigin="anonymous">
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_lux.css" />
    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
    <script src='@Url.Content("~/Scripts/jquery-ui-1.11.3.min.js")' type="text/javascript"></script>

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt="Інфініті ВІДІ Ліберті logo" style="visibility: visible;"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>-->
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Управління ролями</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Управління користувачами</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="IndexAuto">Автомобілі</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Colors" asp-action="Index">Кольори</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Models" asp-action="Index">Моделі</a>
                            </li>
                            <!--
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Drifes" asp-action="Index">Тип приводу</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BodyTypes" asp-action="Index">Тип кузова</a>
                            </li>-->
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="IndexOrder">Замовлення</a>
                            </li>



                            <!--<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="OrderTypes" asp-action="Index">Доступні послуги</a>
                            </li>-->
                            <!-- <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Сервіс</a>
                            </li>-->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Managers" asp-action="Index">Менеджери</a>
                            </li>
                        }

                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Клієнти</a>
                            </li>
                        }
                        @if (!User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="IndexAuto">Автомобілі</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Замовити дзвінок</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>




    @RenderBody()

    <!--<footer class="border-top footer text-muted">



        <div class="container">
            &copy; 2021 - AutoShowWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->

    <footer style="position: relative; ">
        <div class="container">
            <p style="color: #fff; font-size: 17px; font-weight: bold; margin-top: 10px;">МИ В СОЦМЕРЕЖАХ</p>
            <p style="max-width: 404px ; color: #fff; font-size: 15px;">Дізнавайтеся про акції і спецпропозиції, читайте статті, залишайте відгуки, задавайте питання, підписавшись на співтовариства</p>
            <ul style="height: auto !important; justify-content: start; padding-left: 0;" class="networks">
                <li>
                    <a href="">
                        <i class="fas fa-phone-square-alt"></i>
                    </a>
                </li>
                <li style="margin-left: 20PX;">
                    <a href="https://www.facebook.com/InfinitiUkraine/">
                        <i class="fab fa-facebook-square"></i>
                    </a>
                </li>
                <li style="margin-left: 20PX;">
                    <a href="https://www.instagram.com/infiniti.ukraine/">
                        <i class="fab fa-instagram-square"></i>
                    </a>
                </li>
            </ul>
            <div style="position: absolute; content: '';  width: 100%; height: 1px ; background:#000; right: 0; bottom: 50px;"></div>
            <p style=" color: #fff; font-size: 15px; text-align: center; margin-top: 34px;">© 2020 INFINITI “ВІДІ-Ліберті”. Всі права захищені</p>
        </div>
    </footer>

    <script type="text/javascript">
        var cars = [{ model: 'Infiniti QX50', price: 42, year: 21},
        { model: 'Infiniti QX80', price: 65, year: 20 },
        { model: 'Infiniti Q60', price: 52, year: 19 },
        { model: 'Infiniti QX60', price: 46, year: 20 },
        { model: 'Infiniti Q50', price: 30, year: 20 },
        { model: 'Infiniti QX55', price: 46, year: 21}];

        function showGraph(cars, comparator) {
            d3.select('div.diagram').selectAll('div.item').data(cars).enter().append('div')
                .attr('class', 'item').append('span');

            d3.select('div.diagram').selectAll('div.item').data(cars)
                .attr("class", "item").style('width', function (d) { return (d.price * 6) + 'px'; })
                .select('span').text(function (d) { return d.model; });

            d3.select('div.diagram').selectAll('div.item').data(cars).exit().remove();
            if (comparator) {
                d3.select("div.diagram").selectAll("div.item").sort(comparator);
            }
        }

        var compareByYear = function (a, b) { // <-F
            d3.select('div.diagram').selectAll('div.item').data(cars)
                .attr("class", "item").style('width', function (d) { return (d.year * 10) + 'px'; })
                .select('span').text(function (d) { return d.model; });
            return a.year < b.year ? -1 : 1;
        };

        var compareByPrice = function (a, b) { // <-G
            return a.price < b.price ? -1 : 1;
        };

        function sort() {
            var comparator = document.getElementById("select").value;
            switch (comparator) {

                case "compareByYear":
                    comparator = compareByYear;
                    break;
                case "compareByPrice":
                    comparator = compareByPrice;
                    break;
            }

            showGraph(cars, comparator);
        }

        showGraph(cars);
    </script>

    <script async
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7olYNB4namNillixNuAXuifZPmNP4nWE&callback=initMap">
    </script>
    <script>

        // Initialize and add the map
        function initMap() {
            // The location of Uluru
            const uluru = { lat: 49.432086380083824, lng: 26.996913223187423 };
            const ulusecond = { lat: 50.63556708612686, lng: 30.379544956157417 };
            const uluthird = { lat: 50.64561111878802, lng: 30.886353036832414 };
            // The map, centered at Uluru
            const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 5,
                center: uluru, ulusecond, uluthird,
            });
            // The marker, positioned at Uluru
            const marker = new google.maps.Marker({
                position: uluru,
                map: map,
                title: "INFINITI LIGA LUX",
            });
            const marker1 = new google.maps.Marker({
                position: ulusecond,
                map: map,
                title: "AUTO-AKTIV INFINITI",
            });
            const marker2 = new google.maps.Marker({
                position: uluthird,
                map: map,
                title: "INFINITI VIDI LIBERTY",
            });
        }
    </script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>